<?php define( '_ACCESS', 1 ); ?>

<?php

    $page_name = 'blockchain-explorer';
    $page_title = 'Blockchain explorer';
	$page_keywords = '';
	$page_description = '';
	
?>

    <?php include($_SERVER["DOCUMENT_ROOT"]."/inc/header.php"); ?>

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page"><?=$page_title?></li>
        </ol>
    </nav>
	
	<div class="row">
	
        <div class="col-xl-4 push-xl-8 col-lg-12 push-lg-0">

            <nav class="sticky-top">
			
				<form class="wave">
				
					<h3>Check transaction</h3>
 
					<label for="transactionCode">Transaction code</label>
					<input type="text" name="firstName" class="form-control" id="transactionCode" placeholder="Transaction code" required /> 
		
					<br />    
  
					<p><button class="btn btn-primary justify">Check transaction status</button></p>    
  
					<div>Transaction status <span class="text-success">Success</span></div>
					confirmations 5/5     
  
    			</form>
				<!--/.wave-->

            </nav>
			
        </div>
        <!--/.col-->
		
        <div class="col-xl-8 pull-xl-4 col-lg-12 pull-lg-0">
		
			<h2>Latest Blocks</h2>

        	<table class="table table-hover table-striped">
          <thead>
            <tr>
              <th translate="">Height</th>
              <th translate="">Age</th>
              <th class="text-right">
                Transactions
              </th>
              <th class="text-right hidden-xs">
                Generated by
              </th>
              <th class="text-right" translate="">Size</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colspan="5" translate="">Waiting for blocks...</td>
            </tr>
            <tr>
              <td>
                517203
              </td>
              <td>
                3 minutes ago
              </td>
              <td class="text-right">353</td>
              <td class="text-right hidden-xs">
                <a class="" href="/clinic">General Hospital</a>
              </td>
              <td class="text-right">314437</td>
            </tr>
			<tr>
              <td>
                517202
              </td>
              <td>
                6 minutes ago
              </td>
              <td class="text-right">2405</td>
              <td class="text-right hidden-xs">
                <a class="" href="/clinic">General Hospital</a>
              </td>
              <td class="text-right">954431</td>
            </tr>
			<tr>
              <td>
                517201
              </td>
              <td>
                36 minutes ago
              </td>
              <td class="text-right">41</td>
              <td class="text-right hidden-xs">
                <a class="" href="/clinic">General Hospital</a>
              </td>
              <td class="text-right">34425</td>
            </tr>
			<tr>
              <td>
                517200
              </td>
              <td>
                36 minutes ago
              </td>
              <td class="text-right">63</td>
              <td class="text-right hidden-xs">
                <a class="" href="/clinic">General Hospital</a>
              </td>
              <td class="text-right">31773</td>
            </tr>
			<tr>
              <td>
                517199
              </td>
              <td>
                36 minutes ago
              </td>
              <td class="text-right">273</td>
              <td class="text-right hidden-xs">
                <a class="" href="/clinic">General Hospital</a>
              </td>
              <td class="text-right">118489</td>
            </tr>
          </tbody>
		  </table>
		  
		  <br />
 
			<div class="row pagination-line">
            	<div class="col">
					<nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active">
                        <span class="page-link">2<span class="sr-only">(current)</span></span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            		</nav>
            	</div>
            	<!--/.col-->
            	<div class="col"> 
					<em>1-5 / 3154</em>
            	</div>
            	<!--/.col-->
          	</div>
          	<!--/.row-->
			
			<br />
		  
		  <h2>Latest Transactions</h2>
        
			<table class="table table-hover table-striped">
	
          <thead>
            <tr>
              <th>Hash</th>
              <th class="text-right" translate="">Value Out</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td colspan="3" translate="">Waiting for transactions...</td>
            </tr>
            <tr>
              <td>
                64845d87291253212e646b26ba132616a99311093b9c25e4ba19e3edd23540c5
              </td>
              <td class="text-right">
                0.02859148 MPT
              </td>
            </tr>
			<tr>
              <td>
                d72d9c19b6398d172f5bd507999a9e2733bc2afe204e3eec70653e8d8d0b0b8a
              </td>
              <td class="text-right">
                0.02050556 MPT
              </td>
            </tr>
			<tr>
              <td>
                ee7bb71db36b10702346504e70d4750cad3555f56f8869ef5ffd72b8a8ecfe45
              </td>
              <td class="text-right">
                0.1076554 MPT
              </td>
            </tr>
			<tr>
              <td>
                dcddf879fcb7f0f57104547b7814bf3bfe63197264cff5b5f0f3bc0d8eabe756
              </td>
              <td class="text-right">
                0.00030058 MPT
              </td>
            </tr>
			<tr>
              <td>
                4c07b7e621c98efb926382cb56308d4001be2180aa8df5284751b5c2f2971883
              </td>
              <td class="text-right">
                0.28743382 MPT
              </td>
            </tr>
			<tr>
              <td>
                1abd54dacecf8e4e5c903a88a14522fc427b1902f096582f4d037eca660c0a37
              </td>
              <td class="text-right">
                0.03116867 MPT
              </td>
            </tr>
			<tr>
              <td>
                7903ee0ddd33dba0bcabc2abed838a9990354c4a143925d02f8a57d3631ffd53
              </td>
              <td class="text-right">
                0.02133759 MPT
              </td>
            </tr>
			<tr>
              <td>
                501fdaccd77739d4d52e3b62ac73525884013b36f1c004b94e76989dfdb658c1
              </td>
              <td class="text-right">
                0.01063735 MPT
              </td>
            </tr>
			<tr>
              <td>
                60ae7dfaff07fb73893891bde272e0304abcdff3b0e0543000098f7779cc5259
              </td>
              <td class="text-right">
                1.001769 MPT
              </td>
            </tr>
			<tr>
              <td>
                280772ef7294bf113acf516569e987446255303c9548a020be9c5481d4efb093
              </td>
              <td class="text-right">
                0.02030448 MPT
              </td>
            </tr>
          </tbody>
        
</table>    
		  
		  <br />
 
			<div class="row pagination-line">
            	<div class="col">
					<nav aria-label="...">
                <ul class="pagination">
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item active">
                        <span class="page-link">2<span class="sr-only">(current)</span></span>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#">Next</a>
                    </li>
                </ul>
            		</nav>
            	</div>
            	<!--/.col-->
            	<div class="col"> 
					<em>1-5 / 3154</em>
            	</div>
            	<!--/.col-->
          	</div>
          	<!--/.row-->

        </div>
        <!--/.col--> 
		
    </div>
    <!--/.row-->
	
    <?php include($_SERVER["DOCUMENT_ROOT"]."/inc/footer.php"); ?>